### ISSUE TITLE
安装后报orm错误，无法运行

### ISSUE THREAD

**Issue by billyosoror** [hanasa2023/nonebot-plugin-weather-rank#3]
有尝试过nb orm upgrade，仍然报错
关键错误报告：
nonebot_plugin_orm.exception.AutogenerateDiffsDetected: 检测到新的升级操作:
[('add_table',
  Table('nonebot_plugin_weather_rank_weather', MetaData(), Column('id', Integer(), table=<nonebot_plugin_weather_rank_weather>, primary_key=True, nullable=False), Column('group_id', Integer(), table=<nonebot_plugin_weather_rank_weather>, nullable=False), Column('location_code', String(), table=<nonebot_plugin_weather_rank_weather>, nullable=False), Column('location_name', String(), table=<nonebot_plugin_weather_rank_weather>, nullable=False), schema=None))]
![1](https://github.com/user-attachments/assets/5fad0c08-3d2e-47e8-833e-e218f87d56eb)
![2](https://github.com/user-attachments/assets/1d270802-88e4-4ac8-90e8-afa627c2666c)

**Comment by hanasa2023** [comment]
> 有尝试过nb orm upgrade，仍然报错 关键错误报告： nonebot_plugin_orm.exception.AutogenerateDiffsDetected: 检测到新的升级操作: [('add_table', Table('nonebot_plugin_weather_rank_weather', MetaData(), Column('id', Integer(), table=<nonebot_plugin_weather_rank_weather>, primary_key=True, nullable=False), Column('group_id', Integer(), table=<nonebot_plugin_weather_rank_weather>, nullable=False), Column('location_code', String(), table=<nonebot_plugin_weather_rank_weather>, nullable=False), Column('location_name', String(), table=<nonebot_plugin_weather_rank_weather>, nullable=False), schema=None))] ![1](https://private-user-images.githubusercontent.com/53106983/372114902-5fad0c08-3d2e-47e8-833e-e218f87d56eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODgwNjYsIm5iZiI6MTcyNzc4Nzc2NiwicGF0aCI6Ii81MzEwNjk4My8zNzIxMTQ5MDItNWZhZDBjMDgtM2QyZS00N2U4LTgzM2UtZTIxOGY4N2Q1NmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEzMDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMGNmNTc5ODRjZmRhODRkOWI1NDI1ZmJjN2Q3ZjM5Mjc3ZGUyNDlkZDY5NDk3NDE1ZTdlYjZjYzM3ZDMwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YSBfkRKSHONQcbuIz3eHmuhjL_xZpazaju9bAWMgtyE) ![2](https://private-user-images.githubusercontent.com/53106983/372114921-1d270802-88e4-4ac8-90e8-afa627c2666c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODgwNjYsIm5iZiI6MTcyNzc4Nzc2NiwicGF0aCI6Ii81MzEwNjk4My8zNzIxMTQ5MjEtMWQyNzA4MDItODhlNC00YWM4LTkwZTgtYWZhNjI3YzI2NjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEzMDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYTc4NzhkOTYzNTY2MGZhMTM0YzlmODI1ZTRmODQyZWIyZTA0ZDk3ZGE5ZjQxNjY0YjA0NDdlN2EzMDgyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HCtV8n0W_dQgBYQJvEYCvO0WS9D-u3W4wVbf-VYz1CQ)

在最新版本0.1.5中已修复，请注意破坏性更新
